name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '3.13.9'

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  freezed_annotation: ^2.1.0
  http: ^1.1.0
  json_annotation: ^4.6.0
  vector_math: ^2.1.4
