name: bubble_fight
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  core:
    path: ../core
  uuid: ^4.4.0
  rxdart: ^0.27.3
  get_it: ^7.2.0
  vector_math: ^2.1.2
  web_socket_channel: ^2.2.0
  http: ^1.1.0
  flutter_svg: ^2.0.2
  flutter_shake_animated: ^0.0.5
  value_stream_builder: ^1.0.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  min_sdk_android: 21
  image_path_android: "assets/logo_no_background.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/logo_no_background.png"