name: bubble_fight
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  core:
    path: ../core
  uuid: ^3.0.6
  rxdart: ^0.27.3
  get_it: ^7.2.0
  vector_math: ^2.1.2
  web_socket_channel: ^2.2.0
  http: ^1.1.0
  flutter_svg: ^2.0.2
  flutter_shake_animated: ^0.0.5
  value_stream_builder: ^1.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
