name: server
description: A server app using the shelf package and Docker.
publish_to: none
version: 1.0.2

environment:
  sdk: 3.9.2
  flutter: 3.35.5

dependencies:
  args: ^2.0.0
  core:
    path: ../core
  get_it: ^7.2.0
  shelf: ^1.1.0
  shelf_cors_headers: ^0.1.4
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.2
  synchronized: ^3.0.1
  uuid: ^4.5.1
  vector_math: ^2.2.0
  web_socket_channel: ^2.2.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.3.3
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.15.0
