name: server
description: A server app using the shelf package and Docker.
publish_to: none
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0-185.0.dev <4.0.0'

dependencies:
  args: ^2.0.0
  core:
    path: ../core
  shelf: ^1.1.0
  shelf_cors_headers: ^0.1.4
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.2
  uuid: ^3.0.6
  vector_math: ^2.1.2
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
