// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfEdhLlfsp3pSpGGloRIDdVR9pgjBc5mo',
    appId: '1:211280455582:web:449b133d8af7f81b84d88f',
    messagingSenderId: '211280455582',
    projectId: 'bubbles-fight',
    authDomain: 'bubbles-fight.firebaseapp.com',
    storageBucket: 'bubbles-fight.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUMVEnrzT6lbUqCOAVuoDDFFnmiPddPh8',
    appId: '1:211280455582:android:101873310c297a4284d88f',
    messagingSenderId: '211280455582',
    projectId: 'bubbles-fight',
    storageBucket: 'bubbles-fight.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAA4t0BZ0bttWktUIB65fvuPQ86VtEl-I',
    appId: '1:211280455582:ios:eeaad2f8a714b63a84d88f',
    messagingSenderId: '211280455582',
    projectId: 'bubbles-fight',
    storageBucket: 'bubbles-fight.appspot.com',
    iosClientId: '211280455582-jrq3nt9egcuqao4lhosoeqccr9v4slaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbleFight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAA4t0BZ0bttWktUIB65fvuPQ86VtEl-I',
    appId: '1:211280455582:ios:eeaad2f8a714b63a84d88f',
    messagingSenderId: '211280455582',
    projectId: 'bubbles-fight',
    storageBucket: 'bubbles-fight.appspot.com',
    iosClientId: '211280455582-jrq3nt9egcuqao4lhosoeqccr9v4slaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbleFight',
  );
}
